# Format and labels used aim to match those used by Ansible project
# https://github.com/marketplace/actions/github-labeler
- name: bug
  color: "fbca04"
  description: "This issue/PR relates to a bug."
- name: deprecated
  color: "fef2c0"
  description: "This issue/PR relates to a deprecated module."
- name: docs
  color: "4071a5"
  description: "This issue/PR relates to or includes documentation."
- name: enhancement
  color: "ededed"
  description: "This issue/PR relates to a feature request."
- name: feature
  color: "006b75"
  description: "This issue/PR relates to a feature request."
- name: major
  color: "c6476b"
  description: "Marks an important and likely breaking change."
- name: packaging
  color: "4071a5"
  description: "Packaging category"
- name: performance
  color: "555555"
  description: "Relates to product or testing performance."
- name: skip-changelog
  color: "eeeeee"
  description: "Can be missed from the changelog."
- name: stale
  color: "eeeeee"
  description: "Not updated in long time, will be closed soon."
- name: wontfix
  color: "eeeeee"
  description: "This will not be worked on"
- name: test
  color: "0e8a16"
  description: "This PR relates to tests, QA, CI."
- name: gate
  color: "41b6e6"
  description: "Gate PR in Zuul CI"
## more info https://github.com/crazy-max/ghaction-github-labeler
- # automerge
  name: ":bell: automerge"
  color: "8f4fbc"
  description: ""
- # bot
  name: ":robot: bot"
  color: "69cde9"
  description: ""
- # bug
  name: ":bug: bug"
  color: "b60205"
  description: ""
- # dependencies
  name: ":game_die: dependencies"
  color: "0366d6"
  description: ""
- # documentation
  name: ":memo: documentation"
  color: "c5def5"
  description: ""
- # duplicate
  name: ":busts_in_silhouette: duplicate"
  color: "cccccc"
  description: ""
- # enhancement
  name: ":sparkles: enhancement"
  color: "0054ca"
  description: ""
- # feature request
  name: ":bulb: feature request"
  color: "0e8a16"
  description: ""
- # feedback
  name: ":mega: feedback"
  color: "03a9f4"
  description: ""
- # future maybe
  name: ":rocket: future maybe"
  color: "fef2c0"
  description: ""
- # good first issue
  name: ":hatching_chick: good first issue"
  color: "7057ff"
  description: ""
- # help wanted
  name: ":pray: help wanted"
  color: "4caf50"
  description: ""
- # invalid
  name: ":no_entry_sign: invalid"
  color: "e6e6e6"
  description: ""
- # investigate
  name: ":mag: investigate"
  color: "e6625b"
  description: ""
- # needs more info
  name: ":thinking: needs more info"
  color: "795548"
  description: ""
- # pinned
  name: ":pushpin: pinned"
  color: "28008e"
  description: ""
- # question
  name: ":question: question"
  color: "3f51b5"
  description: ""
- # sponsor
  name: ":sparkling_heart: sponsor"
  color: "fedbf0"
  description: ""
- # stale
  name: ":skull: stale"
  color: "237da0"
  description: ""
- # upstream
  name: ":eyes: upstream"
  color: "fbca04"
  description: ""
- # wontfix
  name: ":coffin: wontfix"
  color: "ffffff"
  description: ""
