---
name: auto-label

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'manual trigger'
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  simple-labels:
    runs-on: ubuntu-latest
    steps:
    # labels and minimatch globs to match to apply the label.
    # https://github.com/actions/labeler
    -
      name: checkout
      uses: actions/checkout@v2

    -
      uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: '.github/label-simple-cfg.yml'
        sync-labels: true

  labels:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/marketplace/actions/github-labeler
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: run labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels-cfg.yml
          skip-delete: false
          dry-run: false
          exclude: |
            help*
            *issue

# https://github.com/pycontribs/tender
