---
name: auto-label

on: [push, pull_request, release, pull_request_target, workflow_dispatch]
  # push:
  #   branches: [main]
  # workflow_dispatch:
  #   inputs:
  #     tags:
  #       description: 'manual trigger'
  # pull_request:
  #   types: [ opened, synchronize, reopened ]

jobs:
  simple-labels:
    runs-on: ubuntu-latest
    steps:
    # labels and minimatch globs to match to apply the label.
    # https://github.com/actions/labeler
    -
      name: checkout
      uses: actions/checkout@v2

    -
      uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: '.github/label-simple-cfg.yml'
        sync-labels: false

  labels:
    needs: [ simple-labels ]
    runs-on: ubuntu-latest
    steps:
    # https://github.com/marketplace/actions/github-labeler
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: run labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels-cfg.yml
          skip-delete: true
          dry-run: false
          # exclude: |
          #   help*
          #   *issue
