---
name: auto-label

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'manual trigger'
  pull_request:
    branches: [main]

jobs:
  simple-labels:
    runs-on: ubuntu-latest
    steps:
    # labels and minimatch globs to match to apply the label.
    # https://github.com/actions/labeler
    -
      name: checkout
      uses: actions/checkout@v2

    -
      uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: '.github/label-simple-cfg.yml'
        sync-labels: true

  # labels:
  #   runs-on: ubuntu-latest
  #   steps:
  #   # https://github.com/marketplace/actions/github-labeler
  #   - uses:


# https://github.com/marketplace/actions/github-labeler
# https://github.com/pycontribs/meta/blob/master/.github/labels.yml
# https://github.com/pycontribs/tender
# pull_request_target
