---
name: changelog

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  BRANCH: main
  COMMITTER_BOT: GitHub <noreply@github.com>
  # AUTHOR_BOT: actions-bot <actions-bot@users.noreply.github.com>
  AUTHOR_BOT: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    name: changelog generator
    timeout-minutes: 2
    if: "!contains(github.event.head_commit.message, 'skip')"
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 30
        submodules: 'true'

    # https://github.com/marketplace/actions/tag-changelog
    - name: create changelog text
      uses: loopwerk/conventional-changelog-action@latest
      id: changelog
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        config_file: .github/tag-changelog-config.js

    - name: read changelog.md
      id: readfile
      uses: juliangruber/read-file-action@v1
      with:
        path: CHANGELOG.md

    - name: Write to CHANGELOG.md
      uses: DamianReeves/write-file-action@master
      # if: ${{ steps.git-diff.outputs.count > 0 }}
      with:
        path: CHANGELOG.md
        contents: ${{ steps.changelog.outputs.changelog }}${{ steps.readfile.outputs.content }}
        write-mode: overwrite

    - name: check local changes
      id: diff
      run: |
        changed_files=$(git status --porcelain --untracked-files=all | wc -l)
        echo ::set-output name=count::$changed_files
        echo ::set-output name=created::$(date -u +'%Y-%m-%d')
      shell: bash

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1
      id: tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRY_RUN: true

    -
      name: create pull request
      uses: peter-evans/create-pull-request@v3
      id: cpr
      if: ${{ steps.changelog.outputs.changes }}
      with:
        branch: docs/changelog
        base: ${{ github.head_ref }}
        delete-branch: true
        labels: |
          kind/docs
          :memo: documentation
          :memo: docs
        committer: ${{ env.COMMITTER_BOT }}
        author: ${{ env.AUTHOR_BOT }}
        reviewers: ${{ github.repository_owner }}
        assignees: ${{ github.repository_owner }}
        title: |
          "docs: update changelog "tag:v${{ steps.tag.outputs.tag }} #${{ github.run_number }}" '
        commit-message: |
          'docs: Update CHANGELOG.md "${{ github.workflow }} #${{ github.run_number }}" [skip ci]'
        body: |
          ## Description

          Update CHANGELOG.md

          ${{ steps.changelog.outputs.changelog }}

          ## Update report workflow

          - Updated with *today's* date
          - New Tag: ${{ steps.tag.outputs.new_tag }}
          - Name: ${{ github.workflow }}
          - Run ID: ${{ github.run_id }}
          - Run Number: ${{ github.run_number }}

          _Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request

    - name: check outputs
      if: ${{ steps.changelog.outputs.changes }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

    # - name: Commit and push CHANGELOG.md
    #   uses: EndBug/add-and-commit@v7
    #   with:
    #     add: CHANGELOG.md
    #     message: "chore: Update CHANGELOG.md [skip ci]"
    #     branch:  ${{ github.head_ref }}
        # author_name: github-actions
        # author_email: 41898282+github-actions[bot]@users.noreply.github.com
