---
name: changelog

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  BRANCH: main
  COMMITTER_BOT: GitHub <noreply@github.com>
  AUTHOR_BOT: actions-bot <actions-bot@users.noreply.github.com>

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    name: changelog-generator
    # if: "!contains(github.event.head_commit.message, 'skip')"
    steps:
    # To use this repository's private action, you must check out the repository
    - name: checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    # https://github.com/marketplace/actions/tag-changelog
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.35.0
      id: tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRY_RUN: true

    - name: update changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        headerLabel: "# 📑 Changelog"
        breakingLabel: '### 💥 Breaking'
        enhancementLabel: '### 🚀 Enhancements'
        bugsLabel: '### 🐛 Bug fixes'
        deprecatedLabel: '### ⚠️ Deprecations'
        removedLabel: '### 🔥 Removals'
        securityLabel: '### 🛡️ Security'
        issuesLabel: '### 📁 Other issues'
        prLabel: '### 📁 Other pull requests'
        addSections: '{"documentation":{"prefix":"### 📖 Documentation","labels":["documentation"]},"tests":{"prefix":"### ✅ Testing","labels":["tests"]}}'
        issues: true
        issuesWoLabels: true
        pullRequests: true
        prWoLabels: true
        author: true
        unreleased: true
        compareLink: true
        stripGeneratorNotice: true

    - name: read 'templates/changelog'
      id: ch-template
      uses: juliangruber/read-file-action@v1
      with:
        path: .github/templates/changelog

    # - name: write to changelog.md
    #   uses: DamianReeves/write-file-action@master
    #   with:
    #     path: CHANGELOG.md
    #     contents: |
    #       ${{ steps.ch-template.outputs.content }}${{ steps.ch.outputs.changelog }}
    #     write-mode: overwrite

    - name: read file
      run: |
        cat CHANGELOG.md

    - name: check local changes
      id: diff
      run: |
        changed_files=$(git status --porcelain --untracked-files=all | wc -l)
        echo ::set-output name=count::$changed_files
        echo ::set-output name=created::$(date)
      shell: bash


    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Changelog for tag $
        file_pattern: CHANGELOG.md


    # - name: check outputs
    #   if: ${{ steps.ch.outputs.skipped == 'false' }}
    #   run: |
    #     echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
    #     echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
