name: changelog

on:
  push:
    branches:
    - master
    paths-ignore:
    - "README.md"
    - "CHANGELOG.md"
    - "renovate.json"
  pull_request:
    types: [opened, reopened]
    paths-ignore:
    - "README.md"
    - "CHANGELOG.md"
    - "renovate.json"
  workflow_dispatch:
    inputs:
      tags:
        description: 'manual trigger'
  release:
    types: # This configuration does not affect the page_build event above
    - created

env:
  isForkedRepository: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}


jobs:
  changelog:
    runs-on: ubuntu-latest
    name: update changelog
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 30
        submodules: 'true'

    - name: Generate changelog
      uses: charmixer/auto-changelog-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

