---
name: create-release

on:
  schedule:
  - cron:  "10 23 * * *"
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
    - "README.md"
    - "CHANGELOG.md"
    - "renovate.json"

# consider on pull_request with label 'release'

env:
  INITIAL_VERSION: 0.0.1
  WITH_V: true
  DEFAULT_BUMP: patch
  TO_PUBLISH: ${{ contains(github.event.head_commit.message, 'publish') }}
  TO_DRAFT: ${{ contains(github.event.head_commit.message, 'draft') }}

jobs:

  update-tag:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip') }}

    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
      tag: ${{ steps.tag.outputs.tag }}
      draft: ${{ env.TO_DRAFT }}

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: '0'
        submodules: 'true'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.35.0
      id: tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRY_RUN: ${{ env.TO_DRAFT }}

  draft:
    needs: [ update-tag ]
    runs-on: ubuntu-latest
    # environment variables not yet supported here
    # running this job only for master branch
    if: ${{ !needs.update-tag.outputs.draft && github.ref == 'refs/heads/main' }}

    steps:

    - uses: release-drafter/release-drafter@v5.15.0
      with:
        publish: ${{ env.TO_PUBLISH }}
        prerelease: true
        commitish: ${{ github.ref }}
        tag: ${{ needs.update-tag.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [ update-tag ]
    runs-on: ubuntu-latest
    # environment variables not yet supported here
    # running this job only for master branch
    if: ${{ needs.update-tag.outputs.draft && github.ref == 'refs/heads/main' }}

    steps:

    - uses: release-drafter/release-drafter@v5.15.0
      with:
        publish: true
        prerelease: false
        commitish: ${{ github.ref }}
        tag: ${{ needs.update-tag.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-changelog:
    runs-on: ubuntu-latest
    needs: [ release ]
    name: changelog generator
    timeout-minutes: 5
    if: ${{ !contains(github.event.head_commit.message, 'skip') && needs.update-tag.outputs.draft && github.ref == 'refs/heads/main' }}
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 30
        submodules: 'true'

    # https://github.com/marketplace/actions/tag-changelog
    - name: create changelog text
      uses: loopwerk/conventional-changelog-action@latest
      id: ch
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        config_file: .github/tag-changelog-config.js

    - name: read 'templates/changelog.history'
      id: ch-history
      uses: juliangruber/read-file-action@v1
      with:
        path: .github/templates/changelog.history

    - name: read 'templates/changelog'
      id: ch-template
      uses: juliangruber/read-file-action@v1
      with:
        path: .github/templates/changelog

    - name: write to changelog.md
      uses: DamianReeves/write-file-action@master
      with:
        path: CHANGELOG.md
        contents: |
          ${{ steps.ch-template.outputs.content }}${{ steps.ch.outputs.changelog }}${{ steps.ch-history.outputs.content }}
        write-mode: overwrite

    - name: write to 'templates/changelog.history'
      uses: DamianReeves/write-file-action@master
      with:
        path: .github/templates/changelog.history
        contents: |
          ${{ steps.ch.outputs.changelog }}${{ steps.ch-history.outputs.content }}
        write-mode: overwrite

    - name: check local changes
      id: diff
      run: |
        changed_files=$(git status --porcelain --untracked-files=all | wc -l)
        echo ::set-output name=count::$changed_files
        echo ::set-output name=created::$(date)
      shell: bash

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.35.0
      id: tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRY_RUN: true

    -
      name: create pull request
      uses: peter-evans/create-pull-request@v3
      id: cpr
      if: ${{ steps.ch.outputs.changes }}
      with:
        branch: docs/changelog
        base: ${{ github.head_ref }}
        delete-branch: true
        labels: |
          kind/docs
          :memo: documentation
          :memo: docs
          :bell: approved
          :bell: automerge
          :robot: bot
        committer: ${{ env.COMMITTER_BOT }}
        author: ${{ env.AUTHOR_BOT }}
        title: |
          "docs: update changelog "${{ steps.tag.outputs.tag }} #${{ github.run_number }}" '
        commit-message: |
          'docs: Update CHANGELOG.md "${{ github.workflow }} #${{ github.run_number }}" [skip ci]'
        body: |
          ## Description

          Update CHANGELOG.md

          ${{ steps.changelog.outputs.changelog }}

          ## Update report workflow

          - Updated with *today's* date **`${{ steps.diff.outputs.created }}`**
          - Current Tag: **`${{ steps.tag.outputs.tag }}`**
          - Name: **${{ github.workflow }}**
          - Run ID: **${{ github.run_id }}**
          - Run Number: **${{ github.run_number }}**

          _Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request

    - name: check outputs
      if: ${{ steps.changelog.outputs.changes }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
